---
- hosts: all
  become: true
  tasks:
   - name: stop previous version docker
     shell: docker stop webmagic_demo
   - name: remove stopped container
     shell: docker rm -f webmagic_demo	  
   - name: remove docker images
     shell: docker image rm -f dab8106/webmagic_demo
   - name: create docker image
     shell: docker run -d --name webmagic_demo -p 8090:8080 dab8106/webmagic_demo
