--- 
- 
  become: true
  hosts: all
  tasks: 
    - 
      ignore_errors: true
      name: "stop previous version docker"
      shell: "docker stop ravi_demo"
    - 
      ignore_errors: true
      name: "remove stopped container"
      shell: "docker rm -f ravi_demo"
    - 
      ignore_errors: true
      name: "remove docker images"
      shell: "docker image rm -f banku2706/ravi_demo"
    - 
      name: "create docker image"
      shell: "docker run -d --name ravi_demo -p 8090:8080 banku2706/ravi_demo"
